[build-system]
  requires = ["setuptools"]
  build-backend = "setuptools.build_meta"

[project]
  name = "pawncat"
  version = "0.13.8"
  requires-python = ">=3.6"

[project.scripts]
  pawncat = "pawncat:main"

[tool.setuptools]
  script-files = ["pawncat.py"]
